spring:
  datasource:
    url: jdbc:h2:~/data/hamp
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

---
jwt:
  secret: IknowwhatyoudidinlastsummerandwinterYouKnowThat